export const SONG_STRUCTURE = [
  { start: 0, end: 16.85, mode: 'INTRO', label: 'Initializing Sat-OS...', intensity: 0.1, motionScale: 0.2 },
  { start: 16.85, end: 43.99, mode: 'VERSE_1', label: 'Scanning Fairytales', intensity: 0.3, motionScale: 0.5 },
  { start: 44, end: 68.99, mode: 'BUILD_UP_1', label: 'Signal Weakening', intensity: 0.6, motionScale: 1.2 },
  { start: 69, end: 81.99, mode: 'DROP_1', label: 'SATELLITE CONNECTED', intensity: 1.0, motionScale: 2.5 },
  { start: 82, end: 132.99, mode: 'VERSE_1_CONT', label: 'Orbital Pathing', intensity: 0.4, motionScale: 0.6 },
  { start: 133, end: 157.46, mode: 'REST', label: 'Silent Orbit...', intensity: 0.05, motionScale: 0.1 },
  { start: 157.47, end: 183.99, mode: 'VERSE_2', label: 'Ancient Signals', intensity: 0.3, motionScale: 0.5 },
  { start: 184, end: 195.99, mode: 'LOST_MELODY', label: 'Lost in Space', intensity: 0.1, motionScale: 0.3 },
  { start: 196, end: 208.99, mode: 'BUILD_UP_2', label: 'Re-entry Sequence', intensity: 0.7, motionScale: 1.5 },
  { start: 209, end: 221.99, mode: 'PRE_DROP_2', label: 'Critical Mass', intensity: 0.9, motionScale: 2.0 },
  { start: 222, end: 275.99, mode: 'DROP_2', label: 'SUPERNOVA', intensity: 1.5, motionScale: 3.5 },
  { start: 276, end: 320, mode: 'OUTRO', label: 'Signal Terminated', intensity: 0.0, motionScale: 0.0 }
];

export const LYRIC_TIMINGS = [
  { time: 16.85, text: "Long ago, people prayed for a wish" },
  { time: 19.90, text: "To a star who floated in the sky" },
  { time: 23.02, text: "Only artifacts can be seen there" },
  { time: 26.52, text: "No matter how much we try" },
  { time: 29.65, text: "Instead of natural scintillation" },
  { time: 32.72, text: "They always mechanically blink" },
  { time: 35.96, text: "No one believes fairy tales anymore" },
  { time: 39.61, text: "But our two hearts in sync" },
  { time: 41.29, text: "To wish upon a satellite" },
  { time: 43.66, text: "" },
  { time: 54.15, text: "Wish upon a satellite" },
  { time: 61.28, text: "A satellite" },
  { time: 67.29, text: "Wish upon a satellite" },
  { time: 69.08, text: "" },
  { time: 79.95, text: "Wish upon a satellite" },
  { time: 82.05, text: "" },
  { time: 105.54, text: "Wish upon a satellite" },
  { time: 112.64, text: "A satellite" },
  { time: 118.24, text: "Wish upon a satellite" },
  { time: 125.24, text: "A satellite" },
  { time: 131.08, text: "Wish upon a satellite" },
  { time: 133.70, text: "" },
  { time: 145.24, text: "(Oh-oh-oh-oh-oh-oh)" },
  { time: 151.62, text: "(Oh-oh-oh-oh-oh-oh)" },
  { time: 157.47, text: "一万年前の\"ヒト\"は 星ってやつに祈ったんだって" },
  { time: 163.92, text: "機械めいた信号じゃなく 瞬いたらしいんだ" },
  { time: 170.52, text: "記録か絵の中か おとぎ話にしか無いけど" },
  { time: 176.84, text: "星の代わりに 二つの願いをそっと" },
  { time: 181.86, text: "To wish upon a satellite" },
  { time: 184.34, text: "" },
  { time: 196.47, text: "Oh-oh-oh-oh-oh-ooh" },
  { time: 202.89, text: "Oh-oh-oh-oh-oh-ooh" },
  { time: 207.98, text: "Wish upon a satellite" },
  { time: 210.07, text: "" },
  { time: 215.02, text: "A satellite" },
  { time: 216.42, text: "" },
  { time: 220.62, text: "Wish upon a satellite" },
  { time: 222.59, text: "" },
  { time: 234.88, text: "Oh-oh-oh-oh-oh-ooh" },
  { time: 239.78, text: "Satellite, satellite" },
  { time: 244.70, text: "Satellite wish upon a satellite" },
  { time: 253.10, text: "A satellite" },
  { time: 259.16, text: "Wish upon a satellite" },
  { time: 266.04, text: "A satellite" },
  { time: 271.96, text: "Wish upon a satellite" },
  { time: 274.72, text: "" }
];

export const LINKS_DATA = [
  { platform: 'YouTube', url: 'https://youtube.com/@yots1094', color: '#ff0000', icon: 'Youtube', behavior: 'Pulse on Snare' },
  { platform: 'TikTok', url: 'https://tiktok.com/@dypu119', color: '#00f2fe', icon: 'Video', behavior: 'Chromatic Aberration' }, // Using lucide-react generic Video or similar instead of TikTok explicitly, or custom svg later
  { platform: 'Roblox', url: 'https://roblox.com/users/465013391', color: '#aaaaaa', icon: 'Box', behavior: 'Floating Rotation' },
  { platform: 'Steam', url: 'https://steamcommunity.com/id/stoy109', color: '#0a3461', icon: 'Gamepad2', behavior: 'Scanline Overlay' },
  { platform: 'Instagram', url: 'https://instagram.com/dyp11.9', color: '#c13584', icon: 'Instagram', behavior: 'Radial Sweep Effect' },
];
